# AI Agent Context

## Project Overview
This project is a Monorepo SaaS Application generated by the Bootstrap CLI.
- **Backend**: {{ backend_type }}
- **Deploy**: {{ deploy_target }}

## Code Conventions
- **Infra**: Defined in `infra/` (Fly.io/Docker).
- **API**: defined in `api/openapi.yaml`. This is the source of truth.
- **Tasks**: Use `Taskfile.yml` for all build/test/run commands.

## Current Context
(Use this section to store temporary notes for the AI)
